version: '3.11'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo

volumes:
  mongo-data:
